// Local LLM Integration for AEON Docker Model Runner
// Interfaces with Docker-based local LLM models via HTTP API

export interface LocalLLMMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface LocalLLMRequest {
  messages: LocalLLMMessage[];
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
  stream?: boolean;
}

export interface LocalLLMResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: Array<{
    index: number;
    message: {
      role: string;
      content: string;
    };
    finish_reason: string;
  }>;
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

export interface LocalLLMError {
  error: {
    message: string;
    type: string;
    code?: string;
  };
}

/**
 * Local LLM Client for Docker Model Runner
 * Provides OpenAI-compatible API interface for local models
 */
export class LocalLLMClient {
  private baseUrl: string;
  private timeout: number;

  constructor(baseUrl: string = 'http://localhost:12434', timeout: number = 30000) {
    this.baseUrl = baseUrl.replace(/\/$/, ''); // Remove trailing slash
    this.timeout = timeout;
  }

  /**
   * Send chat completion request to local LLM
   */
  async chatCompletion(request: LocalLLMRequest): Promise<LocalLLMResponse> {
    try {
      const response = await fetch(`${this.baseUrl}/v1/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: JSON.stringify({
          model: 'local-model', // Docker runner handles model selection
          messages: request.messages,
          temperature: request.temperature ?? 0.7,
          max_tokens: request.max_tokens ?? 2000,
          top_p: request.top_p ?? 0.9,
          stream: false, // Non-streaming for now
        }),
        signal: AbortSignal.timeout(this.timeout),
      });

      if (!response.ok) {
        const errorData: LocalLLMError = await response.json().catch(() => ({
          error: {
            message: `HTTP ${response.status}: ${response.statusText}`,
            type: 'http_error',
          },
        }));
        
        throw new Error(`Local LLM API Error: ${errorData.error.message}`);
      }

      const data: LocalLLMResponse = await response.json();
      return data;

    } catch (error) {
      if (error instanceof Error) {
        if (error.name === 'AbortError') {
          throw new Error('Local LLM request timed out. Check if Docker Model Runner is running.');
        }
        if (error.message.includes('fetch')) {
          throw new Error('Failed to connect to Local LLM. Ensure Docker Model Runner is running on the configured host.');
        }
        throw error;
      }
      throw new Error('Unknown error occurred while calling Local LLM');
    }
  }

  /**
   * Check if local LLM service is available
   */
  async healthCheck(): Promise<boolean> {
    try {
      const response = await fetch(`${this.baseUrl}/health`, {
        method: 'GET',
        signal: AbortSignal.timeout(5000),
      });
      return response.ok;
    } catch {
      return false;
    }
  }

  /**
   * Get available models from local LLM service
   */
  async getModels(): Promise<string[]> {
    try {
      const response = await fetch(`${this.baseUrl}/v1/models`, {
        method: 'GET',
        headers: {
          'Accept': 'application/json',
        },
        signal: AbortSignal.timeout(5000),
      });

      if (!response.ok) {
        return ['local-model']; // Fallback
      }

      const data = await response.json();
      return data.data?.map((model: any) => model.id) || ['local-model'];
    } catch {
      return ['local-model']; // Fallback
    }
  }
}

/**
 * Main function to run local LLM with OpenAI-compatible message format
 * This is the primary interface used by agents
 */
export async function runLocalLLM(
  messages: LocalLLMMessage[],
  options: {
    temperature?: number;
    maxTokens?: number;
    topP?: number;
  } = {}
): Promise<string> {
  const localLLMHost = process.env.LOCAL_LLM_HOST || 'http://localhost:12434';
  const client = new LocalLLMClient(localLLMHost);

  // Validate that we have at least one message
  if (!messages || messages.length === 0) {
    throw new Error('At least one message is required for local LLM');
  }

  const request: LocalLLMRequest = {
    messages,
    temperature: options.temperature ?? 0.7,
    max_tokens: options.maxTokens ?? 2000,
    top_p: options.topP ?? 0.9,
  };

  try {
    const response = await client.chatCompletion(request);
    
    if (!response.choices || response.choices.length === 0) {
      throw new Error('No response generated by local LLM');
    }

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error('Empty response from local LLM');
    }

    return content.trim();

  } catch (error) {
    console.error('Local LLM Error:', error);
    
    // Provide helpful error messages for common issues
    if (error instanceof Error) {
      if (error.message.includes('connect') || error.message.includes('ECONNREFUSED')) {
        throw new Error(
          'Cannot connect to Docker Model Runner. Please ensure:\n' +
          '1. Docker is running\n' +
          '2. Model Runner container is started\n' +
          `3. Service is accessible at ${localLLMHost}`
        );
      }
      throw error;
    }
    
    throw new Error('Failed to generate response with local LLM');
  }
}

/**
 * Utility function to convert OpenAI-style messages to local LLM format
 */
export function convertToLocalLLMMessages(messages: any[]): LocalLLMMessage[] {
  return messages.map(msg => ({
    role: msg.role as 'system' | 'user' | 'assistant',
    content: typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content),
  }));
}

/**
 * Check if local LLM is available and healthy
 */
export async function isLocalLLMAvailable(): Promise<boolean> {
  const localLLMHost = process.env.LOCAL_LLM_HOST || 'http://localhost:12434';
  const client = new LocalLLMClient(localLLMHost);
  return await client.healthCheck();
}

// Export singleton instance for convenience
export const localLLMClient = new LocalLLMClient();
