name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  merge_group:

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.0.0

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Create .env.local from example
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env.local
        else
          touch .env.local
        fi

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --network-timeout 300000 --fetch-retries 5

    - name: Run ESLint
      run: pnpm run lint

    - name: Build application
      run: pnpm run build
      env:
        NODE_ENV: production

    - name: Check build output
      run: |
        if [ ! -d ".next" ]; then
          echo "❌ Build failed - .next directory not found"
          exit 1
        fi
        echo "✅ Build completed successfully"